#!/usr/bin/python

from Bio import SeqIO
import sys

infasta = open(sys.argv[1],'r')
query = sys.argv[2]
out = open(sys.argv[3],'w')

for record in SeqIO.parse(infasta,'fasta'):
    if query in record.id:
        SeqIO.write([record],out,'fasta')

out.close()
infasta.close()
